@extends('layouts.admin') @section('title','Product Info | ') @section('content')
<div class="row">
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box">
            <div class="inner">
                <img src="{{ asset('uploads/images/user/avatars/default.jpg') }}" alt="product-image" title="Product Image" style="width: 80px; height: 80px;" />
                    <span class="text-uppercase font-weight-bold">{{ $customer->name }}</span>
            </div>
        </div>
    </div>
    <div class="col-lg-2 col-6">
        <!-- small box -->
        <div class="small-box">
            <div class="inner">
                <h3>{{ $totalInvoices }}</h3>
                    <p>Total Invoices</p>
            </div>
        </div>
    </div>
    <div class="col-lg-2 col-6">
        <!-- small box -->
        <div class="small-box">
            <div class="inner">
                <h3>{{ $total_amount }}
                    </h3>
                    <p>Total Amount</p>
            </div>
        </div>
    </div>
    <div class="col-lg-2 col-6">
        <!-- small box -->
        <div class="small-box">
            <div class="inner">
                <h3>{{ $net_amount }}</h3>
                    <p>Amount Paid</p>
            </div>
        </div>
    </div>
    <div class="col-lg-2 col-6">
        <!-- small box -->
        <div class="small-box">
            <div class="inner">
                <h3>@if ($total_amount > $net_amount)

                    {{ $total_amount - $net_amount }}</h3>
                    <p>Remaining Amount</p>
                    @else
                    {{ $net_amount - $total_amount }}</h3>
                    <p>Alrady Paid Amount</p>

                @endif
            </div>
        </div>
    </div>

</div>


<div class="card">
        <div class="card-body">
            <div class="table-responsive InvoiceTableData" id="InvoiceTableData">
                <table id="table-search" class="table table-hover">
                    <thead>
                        <tr class="text-uppercase">
                            <th scope="col">#</th>
                            <th scope="col">Generated By</th>
                            <th scope="col">Products</th>
                            <th scope="col">total Price</th>
                            <th scope="col">paid</th>
                            <th scope="col">returned</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($invoices as $key => $invoice)
                        <tr id="target_{{ $invoice->id }}">
                            <td>{{ $key+1 }}</td>
                            <td>{{ $invoice->User->name }}</td>
                            <td>{{ $invoice->total_products }}</td>
                            <td>{{ $invoice->total_price }}</td>
                            <td>{{ $invoice->net_amount }}</td>
                            <td>{{ $invoice->return_amount }}</td>

                            <td style="min-width: 135px !important;">
                                <button title="Click to View Invoice" type="button" class="btn btn-info btn-sm InvoiceView" id="ProView" data-Invoiceid="{{ $invoice->id }}">
                                    <i class="fe fe-trash"></i><a href="{{ url('admin/invoices/'.$invoice->id) }}" style="text-decoration: none; color: #fff;">More Info</a>
                                </button>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

@endsection
