@extends('layouts.admin') @section('title','Invoice View | ') @section('content')
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <!-- Main content -->
                <div class="invoice p-3 mb-3">
                    <!-- title row -->
                    <div class="row">
                        <div class="col-12">
                            {{-- <h4>
                                <img src="{{ asset('admin/dist/img/AdminLTELogo.png') }}" width="35px" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: 0.8;" />
                                Shope Name.
                                <small class="float-right">Date: {{ $invoice->created_at }}</small>
                            </h4> --}}
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- info row -->
                    <div class="row invoice-info">
                            <img src="{{ asset('uploads/images/invoice/header1.png') }}" width="100%" alt="">

                        <div class="col-sm-4 invoice-col ">
                            Generated By
                            <address>
                                <strong>{{ $invoice->User->name }}.</strong><br />
                                {{-- 795 Folsom Ave, Suite 600<br />
                                San Francisco, CA 94107<br />
                                Phone: (804) 123-5432<br />
                                Email: info@almasaeedstudio.com --}}
                            </address>
                        </div>
                        <!-- /.col -->
                        <div class="col-sm-4 invoice-col">
                            To
                            <address>
                                <strong>{{ $invoice->Client->name }}</strong><br />
                                Phone: {{ $invoice->Client->phone }}<br />
                            </address>
                        </div>
                        <!-- /.col -->
                        <div class="col-sm-4 invoice-col">
                            <b>Invoice #{{ $invoice->id }}</b><br />
                            <br />
                            <b>Total Products:</b> {{ $invoice->total_products }}<br />
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->

                    <!-- Table row -->
                    <div class="row">
                        <div class="col-12 table-responsive">
                            <table id="" class="table table-hover">
                                <thead>
                                    <tr class="text-uppercase">
                                        <th scope="col">#</th>
                                        <th>Products</th>
                                        <th>price</th>
                                        <th>quantity</th>
                                        <th>total Price</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($invoiceProducts as $key => $invoiceProduct)
                                    <tr id="target_{{ $invoiceProduct->id }}">
                                        <td>{{ $key+1 }}</td>
                                        <td>
                                            @if(isset($invoice->Products)) {{$invoice->Products[$key]->name }} @endif
                                        </td>
                                        <td>{{$invoiceProduct->price }}</td>
                                        <td>{{$invoiceProduct->quantity }}</td>
                                        <td>{{$invoiceProduct->quantity * $invoiceProduct->price }}</td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->

                    <div class="row">
                        <!-- accepted payments column -->
                        <div class="col-6"></div>
                        <!-- /.col -->
                        <div class="col-6">
                            <div class="table-responsive">
                                <table class="table">
                                    <tr>
                                        <th style="width: 50%;">Total:</th>
                                        <td>{{ $invoice->total_price }}</td>
                                    </tr>
                                    <tr>
                                        <th style="width: 50%;">Discount:</th>
                                        <td>{{ $invoice->discount }}</td>
                                    </tr>
                                    <tr>
                                        <th style="width: 50%;">Net Amount:</th>
                                        <td>{{ $invoice->total_price - $invoice->discount }}</td>
                                    </tr>
                                    <tr>
                                        <th>Paid Amount</th>
                                        <td>{{ $invoice->net_amount }}</td>
                                    </tr>
                                    <tr>
                                        @if ($invoice->return_amount <0)

                                        <th>Remaining Amount:</th>
                                        @else
                                        <th>Returned Amount:</th>

                                        @endif
                                        <td>{{ $invoice->return_amount }}</td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                                    <div class="text-right">
                                        <img src="{{ asset('uploads/images/invoice/footer1.png') }}" width="50%" alt="">
                                        <img src="{{ asset('uploads/images/invoice/footer2.png') }}" width="100%" alt="">
                                    </div>


                        <!-- /.col -->
                    </div>
                    <p>This system is generated by <a href="javascript:void(0)" class="font-weight-bold">Oxi-jen</a>. <span class="float-right">Contact :<strong class="">03046118322/03326991009</strong></span></p>
                    <!-- /.row -->

                    <!-- this row will not appear when printing -->
                    <div class="row no-print">
                        <div class="col-12">
                            <a href=""  class=" print btn btn-default"><i class="fas fa-print"></i> Print</a>
                        </div>
                    </div>
                </div>
                <!-- /.invoice -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>
@endsection @section('script')
<script type="text/javascript">
$('.print').on('click',function(){

    window.addEventListener("load", window.print());
})
</script>
@endsection
